# TODO: complete me
services:
  backend:
    build: ./backend
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on: [backend]
    environment:
      - VITE_API_ROOT_URL=http://localhost:8000