# TODO: complete me
services:
  movie-backend:
    build: ./backend
    ports:
      - 8000:8000
  movie-frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - movie-backend
    environment:
      - VITE_API_ROOT_URL=http://localhost:8000